#!/usr/bin/python3
"""Unittest for the Rectangle class.
"""
import unittest
import io
import sys
from models.base import Base
from models.rectangle import Rectangle


class TestRectangleInstantiation(unittest.TestCase):
    """Test cases for creating Rectangle instances."""

    def test_is_base_instance(self):
        """A Rectangle is also an instance of Base."""
        r = Rectangle(10, 2)
        self.assertIsInstance(r, Base)

    def test_default_x_y(self):
        """x and y default to 0."""
        r = Rectangle(10, 2)
        self.assertEqual(r.x, 0)
        self.assertEqual(r.y, 0)

    def test_attributes_assigned(self):
        """width, height, x, y are assigned from the constructor."""
        r = Rectangle(10, 2, 1, 3)
        self.assertEqual(r.width, 10)
        self.assertEqual(r.height, 2)
        self.assertEqual(r.x, 1)
        self.assertEqual(r.y, 3)

    def test_id_passed_to_base(self):
        """The id argument is forwarded to Base's constructor."""
        r = Rectangle(10, 2, 0, 0, 12)
        self.assertEqual(r.id, 12)

    def test_id_none_autogenerated(self):
        """No id argument means an id is auto-generated."""
        r1 = Rectangle(10, 2)
        r2 = Rectangle(2, 10)
        self.assertEqual(r2.id, r1.id + 1)


class TestRectangleValidation(unittest.TestCase):
    """Test cases for Rectangle attribute validation."""

    def test_width_not_int_raises_type_error(self):
        """Non-integer width raises a TypeError."""
        with self.assertRaisesRegex(TypeError, "width must be an integer"):
            Rectangle("10", 2)

    def test_height_not_int_raises_type_error(self):
        """Non-integer height raises a TypeError."""
        with self.assertRaisesRegex(TypeError, "height must be an integer"):
            Rectangle(10, "2")

    def test_width_zero_raises_value_error(self):
        """A width of 0 raises a ValueError."""
        with self.assertRaisesRegex(ValueError, "width must be > 0"):
            Rectangle(0, 2)

    def test_width_negative_raises_value_error(self):
        """A negative width raises a ValueError."""
        with self.assertRaisesRegex(ValueError, "width must be > 0"):
            r = Rectangle(10, 2)
            r.width = -10

    def test_height_zero_raises_value_error(self):
        """A height of 0 raises a ValueError."""
        with self.assertRaisesRegex(ValueError, "height must be > 0"):
            Rectangle(10, 0)

    def test_x_not_int_raises_type_error(self):
        """Non-integer x raises a TypeError."""
        with self.assertRaisesRegex(TypeError, "x must be an integer"):
            r = Rectangle(10, 2)
            r.x = {}

    def test_y_not_int_raises_type_error(self):
        """Non-integer y raises a TypeError."""
        with self.assertRaisesRegex(TypeError, "y must be an integer"):
            Rectangle(10, 2, 0, "1")

    def test_x_negative_raises_value_error(self):
        """A negative x raises a ValueError."""
        with self.assertRaisesRegex(ValueError, "x must be >= 0"):
            Rectangle(10, 2, -3)

    def test_y_negative_raises_value_error(self):
        """A negative y raises a ValueError."""
        with self.assertRaisesRegex(ValueError, "y must be >= 0"):
            Rectangle(10, 2, 3, -1)

    def test_x_zero_is_valid(self):
        """An x of exactly 0 is accepted."""
        r = Rectangle(10, 2, 0, 5)
        self.assertEqual(r.x, 0)

    def test_y_zero_is_valid(self):
        """A y of exactly 0 is accepted."""
        r = Rectangle(10, 2, 5, 0)
        self.assertEqual(r.y, 0)


class TestRectangleArea(unittest.TestCase):
    """Test cases for Rectangle.area."""

    def test_area_simple(self):
        """Area is width multiplied by height."""
        r = Rectangle(3, 2)
        self.assertEqual(r.area(), 6)

    def test_area_with_offset(self):
        """Area ignores x and y offsets."""
        r = Rectangle(8, 7, 0, 0, 12)
        self.assertEqual(r.area(), 56)

    def test_area_square_dimensions(self):
        """Area works when width equals height."""
        r = Rectangle(5, 5)
        self.assertEqual(r.area(), 25)


class TestRectangleDisplay(unittest.TestCase):
    """Test cases for Rectangle.display."""

    def setUp(self):
        """Redirect stdout to capture printed output."""
        self.held_output = io.StringIO()
        self.original_stdout = sys.stdout
        sys.stdout = self.held_output

    def tearDown(self):
        """Restore stdout."""
        sys.stdout = self.original_stdout

    def test_display_no_offset(self):
        """display() with no x/y prints a plain block of '#'."""
        r = Rectangle(4, 2)
        r.display()
        expected = "####\n####\n"
        self.assertEqual(self.held_output.getvalue(), expected)

    def test_display_with_x_offset(self):
        """display() indents each row by x spaces."""
        r = Rectangle(2, 1, 2)
        r.display()
        self.assertEqual(self.held_output.getvalue(), "  ##\n")

    def test_display_with_y_offset(self):
        """display() prints y blank lines before the rectangle."""
        r = Rectangle(2, 1, 0, 3)
        r.display()
        self.assertEqual(self.held_output.getvalue(), "\n\n\n##\n")


class TestRectangleStr(unittest.TestCase):
    """Test cases for Rectangle.__str__."""

    def test_str_format(self):
        """__str__ follows [Rectangle] (id) x/y - width/height."""
        r = Rectangle(4, 6, 2, 1, 12)
        self.assertEqual(str(r), "[Rectangle] (12) 2/1 - 4/6")

    def test_str_default_offsets(self):
        """__str__ reflects default x/y of 0."""
        r = Rectangle(5, 5, 0, 0, 1)
        self.assertEqual(str(r), "[Rectangle] (1) 0/0 - 5/5")


class TestRectangleUpdateArgs(unittest.TestCase):
    """Test cases for Rectangle.update with *args."""

    def test_update_id_only(self):
        """A single positional argument updates only the id."""
        r = Rectangle(10, 10, 10, 10)
        r.update(89)
        self.assertEqual(r.id, 89)
        self.assertEqual(r.width, 10)

    def test_update_id_width(self):
        """Two positional arguments update id and width."""
        r = Rectangle(10, 10, 10, 10)
        r.update(89, 2)
        self.assertEqual((r.id, r.width), (89, 2))

    def test_update_all_positional(self):
        """Five positional arguments update every attribute."""
        r = Rectangle(10, 10, 10, 10)
        r.update(89, 2, 3, 4, 5)
        self.assertEqual(str(r), "[Rectangle] (89) 4/5 - 2/3")

    def test_update_no_args_no_kwargs(self):
        """Calling update() with nothing changes nothing."""
        r = Rectangle(10, 10, 10, 10)
        before = str(r)
        r.update()
        self.assertEqual(str(r), before)


class TestRectangleUpdateKwargs(unittest.TestCase):
    """Test cases for Rectangle.update with **kwargs."""

    def test_update_single_kwarg(self):
        """A single keyword argument updates that attribute."""
        r = Rectangle(10, 10, 10, 10)
        r.update(height=1)
        self.assertEqual(r.height, 1)

    def test_update_multiple_kwargs(self):
        """Multiple keyword arguments update multiple attributes."""
        r = Rectangle(10, 10, 10, 10)
        r.update(y=1, width=2, x=3, id=89)
        self.assertEqual(str(r), "[Rectangle] (89) 3/1 - 2/10")

    def test_args_take_priority_over_kwargs(self):
        """If args is non-empty, kwargs is ignored entirely."""
        r = Rectangle(10, 10, 10, 10)
        r.update(1, width=99)
        self.assertEqual(r.id, 1)
        self.assertEqual(r.width, 10)


class TestRectangleToDictionary(unittest.TestCase):
    """Test cases for Rectangle.to_dictionary."""

    def test_dictionary_keys_and_values(self):
        """to_dictionary returns the correct keys and values."""
        r = Rectangle(10, 2, 1, 9, 1)
        expected = {"id": 1, "width": 10, "height": 2, "x": 1, "y": 9}
        self.assertEqual(r.to_dictionary(), expected)

    def test_dictionary_type(self):
        """to_dictionary returns a dict."""
        r = Rectangle(1, 1)
        self.assertIsInstance(r.to_dictionary(), dict)

    def test_round_trip_equality(self):
        """A Rectangle updated from its own dictionary matches it."""
        r1 = Rectangle(10, 2, 1, 9)
        r2 = Rectangle(1, 1)
        r2.update(**r1.to_dictionary())
        self.assertEqual(str(r1), str(r2))


if __name__ == "__main__":
    unittest.main()
